from typing import Protocol

from app.domain.actions import Effect, ResolutionOption
from app.domain.models import Constraint, Evidence, ProjectSnapshot, ProjectState
from app.domain.runs import ReasoningProposal


class ReasoningEngine(Protocol):
    mode: str

    def interpret(
        self, state: ProjectState, snapshot: ProjectSnapshot, evidence: tuple[Evidence, ...]
    ) -> ReasoningProposal: ...


class ResolutionEngine(Protocol):
    def resolve(
        self, state: ProjectState, constraints: tuple[Constraint, ...]
    ) -> list[ResolutionOption]: ...


class ActionExecutor(Protocol):
    mode: str

    def apply(
        self, state: ProjectState, effects: tuple[Effect, ...], operation_id: str
    ) -> ProjectState: ...
    def verify(
        self, before: ProjectState, after: ProjectState, effects: tuple[Effect, ...]
    ) -> bool: ...


class DurableRuntime(Protocol):
    name: str

    def start(self, run_id: str) -> str: ...
    def signal(self, run_id: str, message: dict, message_id: str) -> None: ...
    def status(self, run_id: str) -> str: ...
    def cancel(self, run_id: str, *, generation: int | None = None) -> None: ...
    def resume(self, run_id: str) -> None: ...
    def close(self) -> None: ...


class FileStore(Protocol):
    def put(self, key: str, content: bytes) -> str: ...
    def read(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...


class WorkflowDriver(Protocol):
    def begin(self, run_id: str, *, generation: int | None = None) -> str: ...
    def advance(self, run_id: str, message: dict, *, generation: int | None = None) -> str: ...
    def expire(self, run_id: str, *, generation: int | None = None) -> str: ...
    def status(self, run_id: str) -> str: ...
